package com.alp.guiswingorderwinalp;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

/**
 * @autor Angel Lorenzo-Penalva Lozano 2ºDAM
 * @versión 1.0
 *
 */
public class GuiSwingOrderWinALP extends JFrame {

    private static final String autor = "Angel Lorenzo-Penalva Lozano";
    private final List<Order> orders = new ArrayList<>();
    
    private static final String DEFAULT_DATE_FORMAT = "yyyy-MM-dd HH:mm:ss"; 
    
    private JLabel lblTotalFinal; 
    private JPanel contentPanel; 
  
    //intentos de poner bordes bien puestos
    private final int MARGIN = 15;
    private final int FRAME_WIDTH = 680;
    private final int FRAME_HEIGHT = 680;
    private final int PANEL_WIDTH = FRAME_WIDTH - (MARGIN * 2);
    private final int PANEL_HEIGHT = FRAME_HEIGHT - (MARGIN * 2) - 35;
    private final int BUTTON_HEIGHT = 35; 
    private final int BUTTON_WIDTH = 130;
    private final int BUTTON_Y1 = 500;
    private final int BUTTON_Y2 = 555;
    
    private final int INPUT_WIDTH_RIGHT = 130;
    private final int FIELD_WIDTH_MAX = 420; 
    private final int FIELD_WIDTH_LEFT = 270; 


    public GuiSwingOrderWinALP() {
        initComponents();
        setupEventListeners();
        updateDateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: DO NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // si quito lo de arriba explota
    private void initComponents() {

        //colores personalizados
        Color buttonStandard = new Color(204,204,204);
        Color fondoClaro = new Color(245, 245, 250); 
        Color fondoContenido = new Color(238,238,238); 
        Color inputBg = Color.WHITE;               
        Color fg = new Color(40, 60, 80);          
        Color botonEsencial = new Color(102,255,102); 
        Color titleColor = new Color(0,0,255);   

        // Inicialización de ButtonGroups
        bgOrderType = new ButtonGroup();
        bgPaymentMethod = new ButtonGroup();

        // Instanciar componentes
        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel(); 
        contentPanel = leftPanel; 
        lblTitle = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnUpdateDate = new javax.swing.JButton();
        lblOrderType = new javax.swing.JLabel();
        rbDine = new javax.swing.JRadioButton();
        rbTakeaway = new javax.swing.JRadioButton();
        lblTableNumber = new javax.swing.JLabel();
        spTable = new javax.swing.JSpinner();
        lblFullName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnCheckEmail = new javax.swing.JButton();
        lblComments = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        lblSubtotal = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        btnCompute = new javax.swing.JButton();
        lblTotalFinal = new javax.swing.JLabel();
        lblPaymentMethod = new javax.swing.JLabel();
        rbCash = new javax.swing.JRadioButton();
        rbCard = new javax.swing.JRadioButton();
        lblTip = new javax.swing.JLabel();
        cbTip = new javax.swing.JComboBox();
        chkInvoice = new javax.swing.JCheckBox();
        btnInfo = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCalc = new javax.swing.JButton(); 
        lblTotal = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        totalPanel = new javax.swing.JPanel();
        lblTotalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TakeOrderApp v.1 por " + autor);
        setBackground(fondoClaro);
        
        setSize(FRAME_WIDTH, FRAME_HEIGHT);
        setResizable(false);
        getContentPane().setLayout(null); 

        //fondo del panel de la ventana
        mainPanel.setBackground(fondoClaro);
        mainPanel.setLayout(null);
        mainPanel.setBounds(0, 0, FRAME_WIDTH, FRAME_HEIGHT);

        //fondo contenido
        contentPanel.setBackground(fondoContenido);
        contentPanel.setLayout(null);
        contentPanel.setBounds(15, 15, 630, 610); 
        
        
        // Título
        lblTitle.setFont(new java.awt.Font("Serif", Font.BOLD | Font.ITALIC, 22));
        lblTitle.setForeground(titleColor);
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("TakeOrderApp por Angel Lorenzo 2ºDAM");
        contentPanel.add(lblTitle);
        lblTitle.setBounds(20, 15, 590, 30);

        // Fecha
        lblDateTime.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblDateTime.setForeground(fg);
        lblDateTime.setText("Fecha y Hora:");
        contentPanel.add(lblDateTime);
        lblDateTime.setBounds(20, 60, 90, 25);

        txtDate.setEditable(false);
        txtDate.setBackground(inputBg);
        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtDate.setForeground(fg);
        txtDate.setBounds(130, 60, FIELD_WIDTH_LEFT, 25); 
        contentPanel.add(txtDate);

        btnUpdateDate.setBackground(buttonStandard);
        btnUpdateDate.setFont(new java.awt.Font("Segoe UI", 0, 11));
        btnUpdateDate.setForeground(fg);
        btnUpdateDate.setText("Actualizar");
        btnUpdateDate.setBounds(420, 60, 180, 25);
        contentPanel.add(btnUpdateDate);

        // Tipo de Pedido 
        lblOrderType.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblOrderType.setForeground(fg);
        lblOrderType.setText("Tipo:");
        contentPanel.add(lblOrderType);
        lblOrderType.setBounds(20, 100, 110, 25);

        rbDine.setBackground(fondoContenido);
        bgOrderType.add(rbDine);
        rbDine.setFont(new java.awt.Font("Segoe UI", 0, 12));
        rbDine.setForeground(fg);
        rbDine.setSelected(true);
        rbDine.setText("Para comer");
        rbDine.setBounds(130, 100, 100, 25);
        contentPanel.add(rbDine);

        rbTakeaway.setBackground(fondoContenido);
        bgOrderType.add(rbTakeaway);
        rbTakeaway.setFont(new java.awt.Font("Segoe UI", 0, 12));
        rbTakeaway.setForeground(fg);
        rbTakeaway.setText("Para llevar");
        rbTakeaway.setBounds(240, 100, 110, 25);
        contentPanel.add(rbTakeaway);

        // Número de Mesa
        lblTableNumber.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblTableNumber.setForeground(fg);
        lblTableNumber.setText("Número de mesa:");
        contentPanel.add(lblTableNumber);
        lblTableNumber.setBounds(360, 100, 120, 25);

        spTable.setFont(new java.awt.Font("Segoe UI", 0, 12));
        spTable.setModel(new javax.swing.SpinnerNumberModel(1, 0, 100, 1)); 
        spTable.setBounds(510, 100, 60, 25);
        contentPanel.add(spTable);

        // Nombre Completo 
        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblFullName.setForeground(fg);
        lblFullName.setText("Nombre completo:");
        contentPanel.add(lblFullName);
        lblFullName.setBounds(20, 140, 120, 25);

        txtName.setBackground(inputBg);
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtName.setForeground(fg);
        txtName.setBounds(130, 140, 470, 25); 
        contentPanel.add(txtName);

        // Email (Y=220)
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblEmail.setForeground(fg);
        lblEmail.setText("Correo electrónico:");
        contentPanel.add(lblEmail);
        lblEmail.setBounds(20, 180, 120, 25);

        txtEmail.setBackground(inputBg);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtEmail.setForeground(fg);
        txtEmail.setBounds(130, 180, 270, 25); 
        contentPanel.add(txtEmail);

        btnCheckEmail.setBackground(buttonStandard);
        btnCheckEmail.setFont(new java.awt.Font("Segoe UI", 0, 11));
        btnCheckEmail.setForeground(fg);
        btnCheckEmail.setText("Comprobar");
        btnCheckEmail.setBounds(420, 180, 180, 25);
        contentPanel.add(btnCheckEmail);

        // Comentarios 
        lblComments.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblComments.setForeground(fg);
        lblComments.setText("Comentarios:");
        contentPanel.add(lblComments);
        lblComments.setBounds(20, 220, 120, 25);

        txtComments.setBackground(inputBg);
        txtComments.setColumns(20);
        txtComments.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtComments.setForeground(fg);
        txtComments.setLineWrap(true);
        txtComments.setRows(5);
        txtComments.setWrapStyleWord(true);
        //jScrollPane1.setViewportView(txtComments); si quiero que tenga scroll

        // Ampliamos el ancho del JScrollPane
        jScrollPane1.setBounds(130, 220, 470, 80);
        contentPanel.add(jScrollPane1);

        // Subtotal 
        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblSubtotal.setForeground(fg);
        lblSubtotal.setText("Total (EUR):");
        contentPanel.add(lblSubtotal);
        lblSubtotal.setBounds(20, 320, 100, 25);

        txtSubtotal.setBackground(inputBg);
        txtSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 12));
        txtSubtotal.setForeground(fg);
        txtSubtotal.setBounds(130, 320, 120, 25);
        contentPanel.add(txtSubtotal);

        // Botón Calcular el Total
        btnCompute.setBackground(botonEsencial);
        btnCompute.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnCompute.setForeground(Color.BLACK);
        btnCompute.setText("Calcular Total");
        btnCompute.setBounds(260, 320, 120, 25);
        contentPanel.add(btnCompute);

        // Etiqueta Total Final 
        lblTotalFinal = new javax.swing.JLabel();
        lblTotalFinal.setFont(new java.awt.Font("SansSerif", Font.BOLD, 14));
        lblTotalFinal.setForeground(titleColor);
        lblTotalFinal.setText("Total final: 0.00 EUR"); 
        lblTotalFinal.setBounds(390, 320, 220, 25); 
        contentPanel.add(lblTotalFinal);
        
        lblTotal = lblTotalFinal;

        // Método de Pago 
        lblPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblPaymentMethod.setForeground(fg);
        lblPaymentMethod.setText("Método de pago:");
        contentPanel.add(lblPaymentMethod);
        lblPaymentMethod.setBounds(20, 360, 120, 25);

        rbCash.setBackground(fondoContenido);
        bgPaymentMethod.add(rbCash);
        rbCash.setFont(new java.awt.Font("Segoe UI", 0, 12));
        rbCash.setForeground(fg);
        rbCash.setSelected(true);
        rbCash.setText("Efectivo");
        rbCash.setBounds(130, 360, 100, 25);
        contentPanel.add(rbCash);

        rbCard.setBackground(fondoContenido);
        bgPaymentMethod.add(rbCard);
        rbCard.setFont(new java.awt.Font("Segoe UI", 0, 12));
        rbCard.setForeground(fg);
        rbCard.setText("Tarjeta");
        rbCard.setBounds(240, 360, 100, 25);
        contentPanel.add(rbCard);

        // Propina y Factura
        lblTip.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblTip.setForeground(fg);
        lblTip.setText("Propinas:");
        contentPanel.add(lblTip);
        lblTip.setBounds(20, 400, 120, 25);

        cbTip.setBackground(inputBg);
        cbTip.setFont(new java.awt.Font("Segoe UI", 0, 12));
        cbTip.setForeground(fg);
        cbTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "5%", "10%", "15%", "20%" }));
        cbTip.setBounds(130, 400, 120, 25);
        contentPanel.add(cbTip);

        chkInvoice.setBackground(fondoContenido);
        chkInvoice.setFont(new java.awt.Font("Segoe UI", 0, 12));
        chkInvoice.setForeground(fg);
        chkInvoice.setText("Solicitar factura");
        chkInvoice.setBounds(260, 400, 200, 25);
        contentPanel.add(chkInvoice);
        

        // Fila 1 de botones  info-about-calc
        btnInfo.setBackground(buttonStandard);
        btnInfo.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnInfo.setForeground(fg);
        btnInfo.setText("Información");
        btnInfo.setBounds(20, 450, 130, 35);
        contentPanel.add(btnInfo);

        btnAbout.setBackground(buttonStandard);
        btnAbout.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnAbout.setForeground(fg);
        btnAbout.setText("Acerca de");
        btnAbout.setBounds(160, 450, 130, 35);
        contentPanel.add(btnAbout);

        btnCalc.setBackground(buttonStandard);
        btnCalc.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnCalc.setForeground(fg);
        btnCalc.setText("Calculadora");
        btnCalc.setBounds(300, 450, 130, 35); 
        contentPanel.add(btnCalc);
        
        // Fila 2 de botones 
        btnViewOrder.setBackground(botonEsencial);
        btnViewOrder.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnViewOrder.setForeground(Color.BLACK);
        btnViewOrder.setText("Guardar pedido");
        btnViewOrder.setBounds(20, 510, 130, 35); 
        contentPanel.add(btnViewOrder);

        JButton btnVerPedidos = new JButton("Ver pedidos");
        btnVerPedidos.setBackground(buttonStandard);
        btnVerPedidos.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnVerPedidos.setForeground(fg);
        btnVerPedidos.addActionListener(e -> mostrarPedidos());
        btnVerPedidos.setBounds(160, 510, 130, 35); 
        contentPanel.add(btnVerPedidos);
                
        btnExit.setBackground(new Color(220, 50, 50)); 
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 13));
        btnExit.setForeground(Color.BLACK);
        btnExit.setText("Salir");
        btnExit.setBounds(300, 510, 130, 35); 
        contentPanel.add(btnExit);
        
        rightPanel.setLayout(null);
        totalPanel.setLayout(null);
        
        // Añadir el panel de contenido al panel principal
        mainPanel.add(contentPanel);
        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, FRAME_WIDTH, FRAME_HEIGHT);
        
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // si quito lo de arriba explota



    // Configura todos los event listeners de los componentes
    private void setupEventListeners() {
        
        btnUpdateDate.addActionListener(e -> updateDateTime());
        btnCheckEmail.addActionListener(e -> checkEmail());
        btnCompute.addActionListener(e -> calculateGrandTotal()); 
        cbTip.addActionListener(e -> calculateGrandTotal());
        
        ActionListener typeListener = e -> {
            boolean take = rbTakeaway.isSelected();
            spTable.setEnabled(!take);
            if (take) {
                spTable.setValue(0);
            } else if ((Integer) spTable.getValue() == 0) {
                spTable.setValue(1);
            }
        };
        rbDine.addActionListener(typeListener);
        rbTakeaway.addActionListener(typeListener);
        btnInfo.addActionListener(e -> showInfoDialog());
        btnViewOrder.addActionListener(e -> saveOrder()); 
        btnCalc.addActionListener(e -> launchCalculator());
        btnAbout.addActionListener(e -> showAbout());
        btnExit.addActionListener(e -> exitApp());
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                exitApp();
            }
        });
    }

    private void updateDateTime() {
        SimpleDateFormat sdf = new SimpleDateFormat(DEFAULT_DATE_FORMAT);
        txtDate.setText(sdf.format(new Date()));
    }

    private boolean isEmailValid(String email) { //expresion correo valido
        Pattern p = Pattern.compile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$");
        return p.matcher(email).matches();
    }

    private void checkEmail() { //checkeo email
        String email = txtEmail.getText().trim();
        if (email.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "El correo está vacío. Rellena el correo tontito.", "Email vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (isEmailValid(email)) {
            JOptionPane.showMessageDialog(this, "Muy bien, este sirve", "Comprobación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Correo NO válido. Ponlo bien macho que no tengo todo el dia.", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void calculateGrandTotal() { //calcular total
        String txt = txtSubtotal.getText().trim();
        double base = 0.0;
        try {
            base = Double.parseDouble(txt);
        } catch (NumberFormatException ex) {
            // mostrar aviso si no está vacío
            if (!txt.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pon un total valido, pedazo de fugitivo de la evolucion", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            }
        }
        //propinicas
        String tipStr = (String) cbTip.getSelectedItem();
        double tipPercent = 0.0;
        if ("5%".equals(tipStr)) {
            tipPercent = 0.05;
        } else if ("10%".equals(tipStr)) {
            tipPercent = 0.10;
        } else if ("15%".equals(tipStr)) {
            tipPercent = 0.15;
        } else if ("20%".equals(tipStr)) {
            tipPercent = 0.20;
        }
        double grand = base + base * tipPercent;
        lblTotal.setText(String.format(Locale.US, "Total final: %.2f EUR", grand));
    }
    
    private void showInfoDialog() {
        JDialog dialog = new JDialog(this, "Información del sistema", true);
        dialog.setSize(480, 350); 
        dialog.setLayout(null);
        dialog.setLocationRelativeTo(this);
        dialog.setResizable(false);
        
        String os = System.getProperty("os.name");
        String osType;
        if (os.toLowerCase().contains("win")) {
            osType = "Windows";
        } else if (os.toLowerCase().contains("mac")) {
            osType = "MacOS";
        } else if (os.toLowerCase().contains("nix") || os.toLowerCase().contains("nux")) {
            osType = "Linux/Unix";
        } else {
            osType = "Otro";
        }

        String currentDateTime = txtDate.getText();
        String username = System.getProperty("user.name");
        String hostname = getHostName();

        //custom de colores
        Color dialogBg = new Color(230, 235, 245);
        Color botonEsencial = new Color(0, 102, 204);
        Color fg = new Color(40, 60, 80);
        dialog.getContentPane().setBackground(dialogBg);
        
        JLabel lblWelcome = new JLabel("¡Bienvenido a TakeOrderApp!", JLabel.CENTER);
        lblWelcome.setBounds(10, 15, 460, 30);
        lblWelcome.setFont(new Font("Segoe UI", Font.BOLD, 16));
        lblWelcome.setForeground(botonEsencial);
        dialog.add(lblWelcome);

        JTextArea info = new JTextArea();
        info.setEditable(false);
        info.setBackground(dialogBg);
        info.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        info.setForeground(fg);
        info.setBounds(15, 55, 440, 200); 
        
        String text = "=======================================\n"
                + "Sistema Operativo: " + osType + "\n"
                + "     Detalles: " + os + "\n"
                + "Fecha y Hora Actuales:\n"
                + "     " + currentDateTime + "\n"
                + "Nombre de la Computadora:\n"
                + "     " + hostname + "\n"
                + "Nombre de Usuario:\n"
                + "     " + username + "\n"
                + "=======================================";
        info.setText(text);
        dialog.add(info);

        JButton btnClose = new JButton("Cerrar");
        btnClose.setBounds(180, 270, 120, 35); 
        btnClose.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btnClose.setBackground(botonEsencial);
        btnClose.setForeground(Color.BLACK);
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(e -> dialog.dispose());
        dialog.add(btnClose);

        dialog.setVisible(true);
    }
    
    private String getHostName() {
        try {
            return java.net.InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            return "Desconocido";
        }
    }

    private void saveOrder() { //guardar el pedido
        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String totalText = txtSubtotal.getText().trim();
        
        // 1. Chequeos antes de guardar
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre del cliente es obligatorio.", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Correo electrónico es obligatorio.", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isEmailValid(email)) {
            JOptionPane.showMessageDialog(this, "Correo electrónico no válido.", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            return;
        }
/* */
        double finalTotal = 0.0;
        double base = 0.0;
        try {
            base = Double.parseDouble(totalText);
            if (base <= 0) {
                JOptionPane.showMessageDialog(this, "El total debe ser mayor que 0.", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Recalcula el total final con propina para pasarlo a Order
            String tipStr = (String) cbTip.getSelectedItem();
            double tipPercent = 0.0;
            if ("5%".equals(tipStr)) {
                tipPercent = 0.05;
            } else if ("10%".equals(tipStr)) {
                tipPercent = 0.10;
            } else if ("15%".equals(tipStr)) {
                tipPercent = 0.15;
            } else if ("20%".equals(tipStr)) {
                tipPercent = 0.20;
            }
            finalTotal = base + base * tipPercent;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe introducir un total válido.", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!rbCash.isSelected() && !rbCard.isSelected()){
            JOptionPane.showMessageDialog(this, "Pon un tipo de pago", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (rbDine.isSelected() && (spTable.getValue() instanceof Integer) && ((Integer) spTable.getValue()) == 0){
            JOptionPane.showMessageDialog(this, "Si es para comer en el restaurante, pon un número de mesa válido (mayor que 0).", "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Actualizar etiqueta del total por si no se hizo con el botón
        lblTotalFinal.setText(String.format(Locale.US, "Total final: %.2f EUR", finalTotal));


        //Construir objeto Order
        String dateTime = txtDate.getText();
        String type = rbTakeaway.isSelected() ? "Para llevar" : "Para comer";
        int tableNumber = (spTable.getValue() instanceof Integer) ? (Integer) spTable.getValue() : Integer.parseInt(spTable.getValue().toString());
        String payment = rbCash.isSelected() ? "Efectivo" : rbCard.isSelected() ? "Tarjeta" : "No seleccionado";
        String tip = (String) cbTip.getSelectedItem();
        boolean invoice = chkInvoice.isSelected();
        String comments = txtComments.getText();

        //construir el objeto order y añadir a la lista
        Order o = new Order(dateTime, type, tableNumber, name, email, comments, finalTotal, payment, tip, invoice);
        orders.add(o);

        //dialogo de exito
        JOptionPane.showMessageDialog(this, "Pedido guardado correctamente.", "Bien hecho nene, no era tan dificil", JOptionPane.INFORMATION_MESSAGE);

        SwingUtilities.invokeLater(() -> {
            try {
                vaciarCampos();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al limpiar campos: " + ex.getMessage(), "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    // Muestra el resumen de todos los pedidos guardados.
    private void mostrarPedidos(){
        StringBuilder all = new StringBuilder();
        int i = 1;
        if (orders.isEmpty()) {
            all.append("No hay pedidos guardados.");
        } else {
            for (Order ord : orders) {
                all.append("--- Pedido #").append(i++).append(" ---\n");
                all.append(ord.toDisplayString()).append('\n');
            }
        }


        JTextArea textArea = new JTextArea(all.toString());
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        textArea.setBackground(new Color(230, 235, 245));
        textArea.setForeground(new Color(40, 60, 80));
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(550, 550));


        JOptionPane.showMessageDialog(this, scrollPane, "Pedidos guardados (" + orders.size() + ")", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void abrirCalculadora() {
    javafx.application.Platform.runLater(() -> {
        try {
            javafx.stage.Stage stage = new javafx.stage.Stage();
            javafx.fxml.FXMLLoader loader = new javafx.fxml.FXMLLoader(getClass().getResource("/com/alp/guiswingorderwinalp/calculator.fxml"));
            javafx.scene.Parent root = loader.load();
            stage.setScene(new javafx.scene.Scene(root));
            stage.setTitle("Calculadora de Pedidos");
            stage.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    });
}

    // Lanza la calculadora según el sistema operativo
    private void launchCalculator() { 
        String os = System.getProperty("os.name").toLowerCase();
        try {
            if (os.contains("win")) {
                Runtime.getRuntime().exec("calc");
            } else if (os.contains("linux") || os.contains("nix")) {
                try {
                    Runtime.getRuntime().exec("mate-calculator");
                } catch (Exception e) {
                    try {
                        Runtime.getRuntime().exec("gnome-calculator");
                    } catch (Exception e2) {
                        Runtime.getRuntime().exec("xcalc");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "La calculadora no está soportada en este sistema operativo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "No se pudo abrir la calculadora tontito: "
                         + ex.getMessage(), "Ta Mal, no se porque, pero Ta Mal", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showAbout() { 
        String aboutMessage = "SISTEMA DE GESTION DE PEDIDOS\n" +
                "Desarrollador:\n" +
                "   " + autor + "\n" +
                "Aplicacion:\n" +
                "   TakeOrderApp\n" +
                "Version:\n" +
                "   1.0 \n" +
                "Fecha:\n" +
                "   Noviembre 2025\n";

        JTextArea textArea = new JTextArea(aboutMessage);
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        textArea.setBackground(new Color(230, 235, 245));
        textArea.setForeground(new Color(40, 60, 80));

        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(400, 350));

        JOptionPane.showMessageDialog(
                this,
                scrollPane,
                "Acerca de la Aplicacion",
                JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void exitApp() {
        int opt = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?\nSe perderán los datos no guardados.",
                "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            String farewellMessage = "Gracias por usar TakeOrderApp. ¡Hasta pronto!";
            JOptionPane.showMessageDialog(this, farewellMessage,
                    "Adiós", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
         if (opt == JOptionPane.NO_OPTION) {
             JOptionPane.showMessageDialog(this, "Menos mal que te he preguntado, sino la lías",
                    "Chao pescao", JOptionPane.INFORMATION_MESSAGE);
         }
    }

    // Limpia los campos de la interfaz para un nuevo pedido.
    private void vaciarCampos() {
        if (txtName != null) txtName.setText("");
        if (txtEmail != null) txtEmail.setText("");
        if (txtComments != null) txtComments.setText("");
        if (txtSubtotal != null) txtSubtotal.setText("");
        if (lblTotalFinal != null) lblTotalFinal.setText("Total final: 0.00 EUR"); 
        if (rbDine != null) rbDine.setSelected(true);
        if (spTable != null) spTable.setValue(1);
        if (rbCash != null) rbCash.setSelected(true); 
        if (rbCard != null) rbCard.setSelected(false);
        if (cbTip != null) cbTip.setSelectedIndex(0);
        if (chkInvoice != null) chkInvoice.setSelected(false);
    }
    
    public static void main(String[] args) {
        javafx.application.Platform.startup(() -> {});
        SwingUtilities.invokeLater(() -> {
            GuiSwingOrderWinALP win = new GuiSwingOrderWinALP();
            win.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // si quito lo de arriba explota
    private javax.swing.ButtonGroup bgOrderType;
    private javax.swing.ButtonGroup bgPaymentMethod;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnCheckEmail;
    private javax.swing.JButton btnCompute;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnUpdateDate;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JComboBox cbTip;
    private javax.swing.JCheckBox chkInvoice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTableNumber;
    private javax.swing.JLabel lblTip;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rbCard;
    private javax.swing.JRadioButton rbCash;
    private javax.swing.JRadioButton rbDine;
    private javax.swing.JRadioButton rbTakeaway;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSpinner spTable;
    private javax.swing.JPanel totalPanel;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSubtotal;
    // si quito lo de abajo explota
    // End of variables declaration//GEN-END:variables
}